/* ======================== 业主管理 ====================  */
/* ====== 业主信息表 =====  */
DROP TABLE IF EXISTS IB_OWNER_FAMILY;
CREATE TABLE IB_OWNER_FAMILY (OWNERID VARCHAR(64), OWNERFAMILYID VARCHAR(64), OWNERFAMILYNAME VARCHAR(64), OWNERFAMILYSEX VARCHAR(8), OWNERFAMILYAGE INT(8), OWNERFAMILYTEL VARCHAR(32), OWNERFAMILYWORKPLACE VARCHAR(128), ID VARCHAR(64), PARENTID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
DROP TABLE IF EXISTS IB_OWNER_INFO;
CREATE TABLE IB_OWNER_INFO (OWNERID VARCHAR(64), OWNERNAME VARCHAR(64), OWNERLOGINNAME VARCHAR(64), OWNERPASSWORD VARCHAR(32), OWNERSEX VARCHAR(8), OWNERAGE INT(8), HOUSEID VARCHAR(8), ROOMID VARCHAR(8), OWNERIDCARD VARCHAR(32), OWNERTEL VARCHAR(32), OWNERHOMEPLACE VARCHAR(64), OWNERWORKPLACE VARCHAR(64), ID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/* ====== 房间信息表 =====  */
DROP TABLE IF EXISTS IB_ROOM_INFO;
CREATE TABLE IB_ROOM_INFO (ROOMID VARCHAR(64), ROOMNAME VARCHAR(64), HOUSEID VARCHAR(64), OWNERID VARCHAR(64), ENTERTIME DATETIME, ROOMTYPE VARCHAR(64), ROOMAREA DOUBLE(12,2), ROOMPURPOSE VARCHAR(64), ID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
/* ====== 楼栋信息表 =====  */
DROP TABLE IF EXISTS IB_HOUSE_INFO;
CREATE TABLE IB_HOUSE_INFO (HOUSEID VARCHAR(64), HOUSENAME VARCHAR(64), BUILDSTARTTIME DATETIME, BUILDENDTIME DATETIME, HOUSEBUG VARCHAR(512), HOUSEAREA DOUBLE(12,2), ID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
