/* ======================== 业务模块组件管理表 ====================  */
/* ========================= 检修任务单表 ========================  */
DROP TABLE IF EXISTS IB_MAINTAINTASK;
CREATE TABLE IB_MAINTAINTASK (TASKNO VARCHAR(64), TASKUSER VARCHAR(64), OVERHAULMETHOD VARCHAR(16), OVERHAULUSER VARCHAR(64), EVENTTIME DATETIME, OVERHAULPLANDAYS INT(8), PLANCOST DOUBLE(12,2), ID VARCHAR(64),  PRIMARY KEY (ID)) ENGINE=INNODB;
